fix: for appwrite 1.4.x
appwrite/sdk-for-flutter pull request #170
Opened 2023-08-31 22:04 UTC by christyjacob4

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-08-31 22:29 UTC, stnguyen90 requested changes

2023-08-31 22:29 UTC, stnguyen90 commented on README.md
> +  appwrite: ^10.0.1
it seems like this PR is missing an update to CHANGELOG.md.

2023-09-01 17:12 UTC, stnguyen90 approved these changes

2023-09-01 18:17 UTC, abnegate approved these changes

2023-09-01 18:17 UTC, merged