chore: bug fixes for Apwrite 1.4.2
appwrite/sdk-for-flutter pull request #172
Opened 2023-09-07 21:27 UTC by christyjacob4

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-09-07 22:01 UTC, stnguyen90 requested changes

2023-09-07 22:01 UTC, stnguyen90 commented on CHANGELOG.md
> +## 10.0.2
Changelog needs to be updated

2023-09-07 23:06 UTC, abnegate approved these changes

2023-09-07 23:59 UTC, stnguyen90 approved these changes

2023-09-08 00:10 UTC, stnguyen90 approved these changes

2023-09-08 00:12 UTC, merged